name: Release Library

on:
  push:
    tags:
      - "v*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
<<<<<<< HEAD

=======
      id-token: write
>>>>>>> ab83820 (fix: CI To publish npm repo)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: 22
          registry-url: https://registry.npmjs.org
=======
          node-version: "22.x"
>>>>>>> ab83820 (fix: CI To publish npm repo)

      - run: npm ci
      - run: npm run build

<<<<<<< HEAD
      - run: npm publish --access public
=======
      # Publish to NPM
      - run: npm publish --provenance --access public
>>>>>>> ab83820 (fix: CI To publish npm repo)

  publish-gpr:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: "@coderoycc"

      - run: npm ci
      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
